
echo 'sm_cvar l4d_no_tank_rush 0' > c1m1_hotel.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > c1m2_streets.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > c1m3_mall.cfg
echo 'sm_cvar l4d_no_tank_rush 1' > c1m4_atrium.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > c2m1_highway.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > c2m2_fairgrounds.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > c2m3_coaster.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > c2m4_barns.cfg
echo 'sm_cvar l4d_no_tank_rush 1' > c2m5_concert.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > c3m1_plankcountry.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > c3m2_swamp.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > c3m3_shantytown.cfg
echo 'sm_cvar l4d_no_tank_rush 1' > c3m4_plantation.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > c4m1_milltown_a.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > c4m2_sugarmill_a.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > c4m3_sugarmill_b.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > c4m4_milltown_b.cfg
echo 'sm_cvar l4d_no_tank_rush 1' > c4m5_milltown_escape.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > c5m1_waterfront.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > c5m2_park.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > c5m3_cemetery.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > c5m4_quarter.cfg
echo 'sm_cvar l4d_no_tank_rush 1' > c5m5_bridge.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > c6m1_riverbank.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > c6m2_bedlam.cfg
echo 'sm_cvar l4d_no_tank_rush 1' > c6m3_port.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > c7m1_docks.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > c7m2_barge.cfg
echo 'sm_cvar l4d_no_tank_rush 1' > c7m3_port.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > c8m1_apartment.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > c8m2_subway.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > c8m3_sewers.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > c8m4_interior.cfg
echo 'sm_cvar l4d_no_tank_rush 1' > c8m5_rooftop.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > c9m1_alleys.cfg
echo 'sm_cvar l4d_no_tank_rush 1' > c9m2_lots.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > c10m1_caves.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > c10m2_drainage.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > c10m3_ranchhouse.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > c10m4_mainstreet.cfg
echo 'sm_cvar l4d_no_tank_rush 1' > c10m5_houseboat.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > c11m1_greenhouse.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > c11m2_offices.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > c11m3_garage.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > c11m4_terminal.cfg
echo 'sm_cvar l4d_no_tank_rush 1' > c11m5_runway.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > c12m1_hilltop.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > c12m2_traintunnel.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > c12m3_bridge.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > c12m4_barn.cfg
echo 'sm_cvar l4d_no_tank_rush 1' > c12m5_cornfield.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > c13m1_alpinecreek.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > c13m2_southpinestream.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > c13m3_memorialbridge.cfg
echo 'sm_cvar l4d_no_tank_rush 1' > c13m4_cutthroatcreek.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > 2019_M1b.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > 2019_M2b.cfg
echo 'sm_cvar l4d_no_tank_rush 1' > 2019_M3b.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > bhm1_outskirts.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > bhm2_dam.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > bhm3_station.cfg
echo 'sm_cvar l4d_no_tank_rush 1' > bhm4_base.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > bloodtracks_01.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > bloodtracks_02.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > bloodtracks_03.cfg
echo 'sm_cvar l4d_no_tank_rush 1' > bloodtracks_04.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > l4d2_bts01_forest.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > l4d2_bts02_station.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > l4d2_bts03_town.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > l4d2_bts04_cinema.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > l4d2_bts05_church.cfg
echo 'sm_cvar l4d_no_tank_rush 1' > l4d2_bts06_school.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > cwm1_intro.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > cwm2_warehouse.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > cwm3_drain.cfg
echo 'sm_cvar l4d_no_tank_rush 1' > cwm4_building.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > cotd01_apartments.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > cotd02_warehouse.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > cotd03_mall.cfg
echo 'sm_cvar l4d_no_tank_rush 1' > cotd04_rooftop.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > l4d2_city17_01.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > l4d2_city17_02.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > l4d2_city17_03.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > l4d2_city17_04.cfg
echo 'sm_cvar l4d_no_tank_rush 1' > l4d2_city17_05.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > l4d2_ff01_woods.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > l4d2_ff02_factory.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > l4d2_ff03_highway.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > l4d2_ff04_plant.cfg
echo 'sm_cvar l4d_no_tank_rush 1' > l4d2_ff05_station.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > dkr_m1_motel.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > dkr_m2_carnival.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > dkr_m3_tunneloflove.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > dkr_m4_ferris.cfg
echo 'sm_cvar l4d_no_tank_rush 1' > dkr_m5_stadium.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > l4d2_darkblood01_tanker.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > l4d2_darkblood02_engine.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > l4d2_darkblood03_platform.cfg
echo 'sm_cvar l4d_no_tank_rush 1' > l4d2_darkblood04_extraction.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > l4d2_daybreak01_hotel.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > l4d2_daybreak02_coastline.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > l4d2_daybreak03_bridge.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > l4d2_daybreak04_cruise.cfg
echo 'sm_cvar l4d_no_tank_rush 1' > l4d2_daybreak05_rescue.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > ddg1_tower_v2_1.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > ddg2_gristmill_v2.cfg
echo 'sm_cvar l4d_no_tank_rush 1' > ddg3_bluff_v2_1.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > deadbeat01_forest.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > deadbeat02_alley.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > deadbeat03_street.cfg
echo 'sm_cvar l4d_no_tank_rush 1' > deadbeat04_park.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > l4d_dbd2dc_anna_is_gone.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > l4d_dbd2dc_the_mall.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > l4d_dbd2dc_clean_up.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > l4d_dbd2dc_undead_center.cfg
echo 'sm_cvar l4d_no_tank_rush 1' > l4d_dbd2dc_new_dawn.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > death_sentence_1.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > death_sentence_2.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > death_sentence_3.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > death_sentence_4.cfg
echo 'sm_cvar l4d_no_tank_rush 1' > death_sentence_5.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > cdta_01detour.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > cdta_02road.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > cdta_03warehouse.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > cdta_04onarail.cfg
echo 'sm_cvar l4d_no_tank_rush 1' > cdta_05finalroad.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > dprm1_milltown_a.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > dprm2_sugarmill_a.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > dprm3_sugarmill_b.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > dprm4_milltown_b.cfg
echo 'sm_cvar l4d_no_tank_rush 1' > dprm5_milltown_escape.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > ec01_outlets.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > ec02_dam.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > ec03_village.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > ec04_powerstation.cfg
echo 'sm_cvar l4d_no_tank_rush 1' > ec05_quarry.cfg
echo 'sm_cvar l4d_no_tank_rush 1' > c1m1_hotel_d_insane.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > hf01_theforest.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > hf02_thesteeple.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > hf03_themansion.cfg
echo 'sm_cvar l4d_no_tank_rush 1' > hf04_escape.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > aircrash.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > rivermotel.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > outskirts.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > cityhall.cfg
echo 'sm_cvar l4d_no_tank_rush 1' > bombshelter.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > highway01_apt_20130613.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > highway02_megamart_20130613.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > highway03_hood01_20130614.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > highway04_afb_a_02_20130616.cfg
echo 'sm_cvar l4d_no_tank_rush 1' > highway05_afb02_20130820.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > l4d_ihm01_forest.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > l4d_ihm02_manor.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > l4d_ihm03_underground.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > l4d_ihm04_lumberyard.cfg
echo 'sm_cvar l4d_no_tank_rush 1' > l4d_ihm05_lakeside.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > jsarena201_town.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > jsarena202_alley.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > jsarena203_roof.cfg
echo 'sm_cvar l4d_no_tank_rush 1' > jsarena204_arena.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > l4d2_diescraper1_apartment_361.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > l4d2_diescraper2_streets_361.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > l4d2_diescraper3_mid_361.cfg
echo 'sm_cvar l4d_no_tank_rush 1' > l4d2_diescraper4_top_361.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > l4d_149_1.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > l4d_149_2.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > l4d_149_3.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > l4d_149_4.cfg
echo 'sm_cvar l4d_no_tank_rush 1' > l4d_149_5.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > l4d_tbm_1.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > l4d_tbm_2.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > l4d_tbm_3.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > l4d_tbm_4.cfg
echo 'sm_cvar l4d_no_tank_rush 1' > l4d_tbm_5.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > x1m1_cliffs.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > x1m2_path.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > x1m3_city.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > x1m4_forest.cfg
echo 'sm_cvar l4d_no_tank_rush 1' > x1m5_salvation.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > l4d_ravenholm01_blackmesa.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > l4d_ravenholm02_traptown.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > l4d_ravenholm03_church.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > l4d_ravenholm04_cavern.cfg
echo 'sm_cvar l4d_no_tank_rush 1' > l4d_ravenholm05_docks.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > l4d2_stadium1_apartment.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > l4d2_vs_stadium2_riverwalk.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > l4d2_stadium3_city1.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > l4d2_stadium4_city2.cfg
echo 'sm_cvar l4d_no_tank_rush 1' > l4d2_stadium5_stadium.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > eu01_residential_b16.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > eu02_castle_b16.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > eu03_oldtown_b16.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > eu04_freeway_b16.cfg
echo 'sm_cvar l4d_no_tank_rush 1' > eu05_train_b16.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > uz_crash.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > uz_town.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > uz_desert.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > uz_bunker.cfg
echo 'sm_cvar l4d_no_tank_rush 1' > uz_escape.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > uf1_boulevard.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > uf2_rooftops.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > uf3_harbor.cfg
echo 'sm_cvar l4d_no_tank_rush 1' > uf4_airfield.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > srocchurch.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > plaza_espana.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > maria_cristina.cfg
echo 'sm_cvar l4d_no_tank_rush 1' > mnac.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > wfp1_track.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > wfp2_horn.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > wfp3_mill.cfg
echo 'sm_cvar l4d_no_tank_rush 1' > wfp4_commstation.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > c1_mario1_1.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > c1_mario1_2.cfg
echo 'sm_cvar l4d_no_tank_rush 0' > c1_mario1_3.cfg
echo 'sm_cvar l4d_no_tank_rush 1' > c1_mario1_4.cfg
